# Generated by Django 2.0.2 on 2018-03-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readandpick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
