# Generated by Django 2.0.2 on 2018-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readandpick', '0002_auto_20180308_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_name',
            field=models.CharField(default='No Image available', max_length=255, verbose_name='image_name'),
        ),
    ]
